name: user_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

# ESTA SECCIÓN SOLUCIONA TU ERROR DE LA TERMINAL:
environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_tachi.png
    - assets/images/logo_tachi_apps.png

# Configuración del ícono adaptativo separando las imágenes
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_tachi.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#061328"
  adaptive_icon_foreground: "assets/images/logo_tachi_apps.png"
